### ISSUE TITLE
Address canvas dependencies on OS X

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#209]
On OS X when you try to do a fresh install of the system you get an error about the canvas library not properly building:

```
[4/4] 📃  Building fresh packages...
warning Error running install script for optional dependency: "/usr/local/src/xmacroscope/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /usr/local/src/xmacroscope/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.8.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/src/xmacroscope/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/xmacroscope/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/xmacroscope/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bkennedy/.node-gyp/10.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bkennedy/.node-gyp/10.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/src/xmacroscope/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/bkennedy/.node-gyp/10.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/src/xmacroscope/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/src/xmacroscope/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command \"/Users/bkennedy/.nvm/versions/node/v10.8.0/bin/node\" \"/usr/local/src/xmacroscope/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /usr/local/src/xmacroscope/node_modules/canvas
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```
This is not a blocking error, but it's disconcerting to see during the install process.

I believe that this is coming from vega's canvas version. This is a lower priority issue, but maybe a Vega upgrade would address the issue. Or maybe we have some other global dependencies that are needed for the system.

**Comment by bryankennedy** [comment]
There's some conversation here about requiring the `pkg-config` tool at the OS level.
https://github.com/Automattic/node-canvas/issues/822
